config/routes.rb
Rails.application.routes.draw do
  # ------------ routes détaillées ------------
  get "pets", to: "pets#index"
  get "pets/new", to: "pets#new", as: "new_pet"
  get "pets/:id", to: "pets#show", as: "pet"
  post "pets", to: "pets#create"
  get    "pets/:id/edit", to: "pets#edit", as: "edit_pet"
  patch  "pets/:id",      to: "pets#update"
  delete "pets/:id",      to: "pets#destroy"

  # ------------ Autre possibilité ------------
  # root to: "pets#index"
  # resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["cat", "tiger", "parrot", "bug"]
  validates :name, presence: true
  validates :found_on, presence: true
  validates :species, inclusion: { in: SPECIES}

  def found_days_ago
    (Date.today - found_on).to_i
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :found_on, :species)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
    <%= simple_form_for @pet do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :species, collection: Pet::SPECIES %>
          <%= f.input :found_on %>
          <%= f.submit class: "btn btn-primary mt-4" %>
        <% end %>

app/views/pets/edit.html.erb
<div class="container w-50">
  <h1 class="m-5">Edit <%= @pet.name %></h1>

  <%= render "form" %>

app/views/pets/index.html.erb
<div class="container w-50 d-flex justify-content-center">
  <div>
    <h1 class="my-5">All the pets found</h1>

    <ul>
      <% @pets.each do |pet| %>
        <li><%= link_to pet.name, pet_path(pet) %> --> found <%= pet.found_days_ago %> days ago</li>
      <% end %>
    </ul>

    <%= link_to "New Pet discovered", new_pet_path, class: "mt-5 w-100 btn btn-primary" %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container w-50">
  <h1 class="m-5">Create a new pet</h1>
  <%= render "form" %>
</div>

app/views/pets/show.html.erb
<div class="container w-50">
  <h1 class="my-5">Details of <%= @pet.name %></h1>

  <p>Species:<%= @pet.species %></p>

  <p>Found <%= @pet.found_days_ago %> days ago, on <%= @pet.found_on %></p>

  <%= link_to "Home", pets_path, class: "btn btn-primary" %>
  <%= link_to "Edit", edit_pet_path(@pet), class: "btn btn-primary" %>
  <%= link_to "Remove", pet_path(@pet), class: "btn btn-warning", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>